name: hcd
channels:
  - conda-forge
  - defaults
dependencies:
  - black=21.7b0
  - flake8=4.0.1
  - graphviz=2.49.1
  - imbalanced-learn=0.8.1
  - jupyter=1.0.0
  - matplotlib=3.4.3
  - numpy=1.19.5
  - opencv=4.5.3
  - pandas=1.3.4
  - pillow=8.3.2
  - pip=21.3.1
  - pre-commit=2.15.0
  - pydot=1.4.2
  - python=3.9.7
  - scikit-learn=1.0
  - seaborn=0.11.2
  - pip:
    - kaggle==1.5.12
    - tensorboard==2.6.0
    - tensorflow==2.6.0
