name: hcd-m1
channels:
  - apple
  - conda-forge
dependencies:
  - graphviz=2.49.1
  - imbalanced-learn=0.8.1
  - jupyter=1.0.0
  - matplotlib=3.4.3
  - numpy=1.19.5
  - opencv=4.5.3
  - pandas=1.3.4
  - pillow=8.3.2
  - pip=21.3
  - pydot=1.4.2
  - scikit-learn=1.0
  - seaborn=0.11.2
  - tensorboard=2.6.0
  - tensorflow-deps=2.5.0
  - pip:
    - tensorflow-macos==2.5.0
    - tensorflow-metal==0.1.2
